import 'package:easyflow/layers/modules/equipment/model/equipment_model.dart';

class EquipmentProvider {}

final dummyEquipments = [
  EquipmentModel(
    id: 1,
    tumble: "111111",
    name: "Aspire A315",
    model: "Acer",
    description: ["4GB", "i5 10gen", "128GB SSD"],
    isDisponible: true,
  ),
  EquipmentModel(
    id: 1,
    tumble: "111111",
    name: "Aspire A315",
    model: "Acer",
    description: ["4GB", "i5 10gen", "128GB SSD"],
    isDisponible: true,
  ),
  EquipmentModel(
    id: 1,
    tumble: "111111",
    name: "Aspire A315",
    model: "Acer",
    description: ["4GB", "i5 10gen", "128GB SSD"],
    isDisponible: true,
  ),
  EquipmentModel(
    id: 1,
    tumble: "111111",
    name: "Aspire A315",
    model: "Acer",
    description: ["4GB", "i5 10gen", "128GB SSD"],
    isDisponible: false,
  ),
  EquipmentModel(
    id: 1,
    tumble: "111111",
    name: "Aspire A315",
    model: "Acer",
    description: ["4GB", "i5 10gen", "128GB SSD"],
    isDisponible: false,
  ),
  EquipmentModel(
    id: 1,
    tumble: "111111",
    name: "Aspire A315",
    model: "Acer",
    description: ["4GB", "i5 10gen", "128GB SSD"],
    isDisponible: false,
  ),
  EquipmentModel(
    id: 1,
    tumble: "111111",
    name: "Aspire A315",
    model: "Acer",
    description: ["4GB", "i5 10gen", "128GB SSD"],
    isDisponible: true,
  ),
  EquipmentModel(
    id: 1,
    tumble: "111111",
    name: "Aspire A315",
    model: "Acer",
    description: ["4GB", "i5 10gen", "128GB SSD"],
    isDisponible: true,
  ),
  EquipmentModel(
    id: 1,
    tumble: "111111",
    name: "Aspire A315",
    model: "Acer",
    description: ["4GB", "i5 10gen", "128GB SSD"],
    isDisponible: false,
  ),
  EquipmentModel(
    id: 1,
    tumble: "111111",
    name: "Aspire A315",
    model: "Acer",
    description: ["4GB", "i5 10gen", "128GB SSD"],
    isDisponible: false,
  ),
  EquipmentModel(
    id: 1,
    tumble: "111111",
    name: "Aspire A315",
    model: "Acer",
    description: ["4GB", "i5 10gen", "128GB SSD"],
    isDisponible: false,
  ),
];
