import '../../data/model/representatives_model.dart';

final List<RepresentativesModel> representativesData = [
  RepresentativesModel(
    uid: "1",
    name: "Julia Fonseca",
    imageUrl: "assets/images/julia.png",
    email: "juliafonseca@gmail.com",
    area: "Q&A",
    turn: "Segunda-Feira. Turno Manha",
  ),
  RepresentativesModel(
    uid: "0",
    name: "Mário Jamisson",
    imageUrl: "assets/images/mario.png",
    email: "mariojamisson@gmail.com",
    area: "Games",
    turn: "Segunda-Feira. Turno Manha",
  ),
  RepresentativesModel(
    uid: "1",
    name: "Julia Fonseca",
    imageUrl: "assets/images/julia.png",
    email: "juliafonseca@gmail.com",
    area: "Q&A",
    turn: "Segunda-Feira. Turno Manha",
  ),
  RepresentativesModel(
    uid: "2",
    name: "Raul Pereira",
    imageUrl: "assets/images/raul.png",
    email: "raulpereira@gmail.com",
    area: "UX-UI",
    turn: "Segunda-Feira. Turno Manha",
  ),
  RepresentativesModel(
    uid: "3",
    name: "Rubens Abraão",
    imageUrl: "assets/images/abraao.png",
    email: "rubensabraao@gmail.com",
    area: "Representante Líder",
    turn: "Segunda-Feira. Turno Manha",
  ),
  RepresentativesModel(
    uid: "2",
    name: "Raul Pereira",
    imageUrl: "assets/images/raul.png",
    email: "raulpereira@gmail.com",
    area: "UX-UI",
    turn: "Segunda-Feira. Turno Manha",
  ),
  RepresentativesModel(
    uid: "3",
    name: "Rubens Abraão",
    imageUrl: "assets/images/abraao.png",
    email: "rubensabraao@gmail.com",
    area: "Representante Líder",
    turn: "Segunda-Feira. Turno Manha",
  ),
  RepresentativesModel(
    uid: "3",
    name: "Rubens Abraão",
    imageUrl: "assets/images/abraao.png",
    email: "rubensabraao@gmail.com",
    area: "Representante Líder",
    turn: "Segunda-Feira. Turno Manha",
  ),
  RepresentativesModel(
    uid: "2",
    name: "Raul Pereira",
    imageUrl: "assets/images/raul.png",
    email: "raulpereira@gmail.com",
    area: "UX-UI",
    turn: "Segunda-Feira. Turno Manha",
  ),
  RepresentativesModel(
    uid: "1",
    name: "Julia Fonseca",
    imageUrl: "assets/images/julia.png",
    email: "juliafonseca@gmail.com",
    area: "Q&A",
    turn: "Segunda-Feira. Turno Manha",
  ),
];
